### PR TITLE
Updated to use tmysql4

### PR DESCRIPTION
**Pull request by Celant**
Updated the SQL code to use tMySQL4
Fixed the random new lines
Satisfies issue #6

### CODE REVIEW

**Comment by blastehh** [comment]
Did you test this?
it still has require for pmysql at the top

**Comment by Celant** [comment]
Yeah this was the version I'm currently using on my server, thought you might want the changes.
Fixing the require now.

**Comment by Celant** [comment]
@blastehh the require has been removed. Re-review please.

**Comment by blastehh** [comment]
I'll have a test later, but you should replace it with tmysql instead of
removing the require. This will only work if other addons are loading the
module for you.

**Comment by Dimentio** [comment]
I've been using it, it seems to work fine.

**Comment by Celant** [comment]
@blastehh how did testing this go? My server is still running with this, no issues so far.

**Comment by Dimentio** [comment]
Seems to be fine, I'm trying to add my own little touch. (Trying to kick user at CheckPassword hook)

**Comment by blastehh** [comment]
I won't have time to test as I'm going to be away for 2 weeks, I'll merge this now and you can complain later if it doesn't work :)

I don't think it's possible to kick via checkpassword hook since the ban lookup is async, there's no way to return an answer without locking up the server while the query is running.

**Comment by Dimentio** [comment]
That would be saddening... I'll report if I manage to make it work.

**Comment by Dimentio** [comment]
I've managed to do what I wanted!
I don't think I'm a great coder or anything but if anybody interested here's what I've done http://pastebin.com/2XAaejdf

**Comment by blastehh** [comment]
Interesting, so does that kick them during the loading screen?

**Comment by Dimentio** [comment]
It's instant, the moment they connect they are kicked.

**Pull request merged**
